### ISSUE TITLE
Admin styles leaking in gdocs preview

### ISSUE THREAD

**Issue by mlbrgl** [owid/owid-grapher#1749]

**Comment by ikesau** [comment]
I'm seeing it in places like

![image](https://user-images.githubusercontent.com/11844404/199831112-c92a7590-34ce-4b9d-ae03-275c31408e70.png)


I think adding `.GrapherComponent` to the rules in places like `packages/@ourworldindata/grapher/src/captionedChart/CaptionedChart.scss` should fix the conflicts.

e.g

```css
.GrapherComponent .HeaderHTML {
    padding: 15px;
    ...
}
```
