### ISSUE TITLE
Project data pages: create a data page component and a preview page for it

### ISSUE THREAD

**Issue by danyx23** [owid/owid-grapher#1947]
In the first cycle we want to get to a point where we have a react component that renders something relatively similar to the [sketches for data pages](https://www.figma.com/proto/9bQW46okOjxeJtismQQdPu/%5BDesktop%5D-Screens-1.0?page-id=3414%3A26514&node-id=3417%3A26803&viewport=603%2C599%2C0.21&scaling=min-zoom&starting-point-node-id=3414%3A26515).

A full data page will need a lot of information - it will be passed a "page context" JSON object that contains the full variable metadata and other information. The shape of this other information is to be determined as part of this project. Eventually this page context will be created in the ETL for variables; but for fast iteration initially, it will be useful to iterate on this quickly. A YAML file  per variable in a new github repo might be a good solution for the work in this first cycle.

We will need a way to preview a data page quickly when the page context YAML file is edited - probably a temporary page in the admin is the most useful for this job.

For the first cycle, the main focus is not on matching the design very faithfully in terms of aesthetics but rather on building out the components and the data structures required to show everything that is visible in the design.

The changes to Grapher so that it can display without making charts and without tabs are described in #1948.

One big question that we want to answer in the data pages project is how to deal with small pieces of (technical) text that apply to many variables. For this it would be useful to experiment with allowing certain parts of the page context JSON/YAML to point to google docs documents by id/url which will then be fetched and shown inline, like so:

```yaml
variableMetadata:
  name: Life expetancy
  ...
technicalText:
  - https://docs.google.com/document/d/1wrXxKFgkpy8E5etN9jEJOTmZKtrld9AmllNY8DQM1-g/edit?usp=share_link
  - https://docs.google.com/document/d/1WGXdlG0-mX0dnRi5S4ubrX0QS37BHFnQ3bZT07GxrXE/edit?usp=share_link
```

There are several things that are unclear about this, but having this capability would allow authors to write often used text in gdocs where they like to write and give feedback, and data managers to bulk curate relevant pieces of writing and link them in the relevant places.
