### ISSUE TITLE
CSS Grid container is incorrectly sized on Windows

### ISSUE THREAD

**Issue by ikesau** [owid/owid-grapher#2419]
Our grid system has a class which allows us to reliably have 12 centred columns that span 1280px, while also allowing us to go full-width when necessary:

```css
.grid-cols-12-full-width {
  --outer-column-width: calc((50vw - 640px - var(--grid-gap)));
  grid-template-columns: var(--outer-column-width) repeat(12, 1fr) var(--outer-column-width);
}
```

<img width="1512" alt="image" src="https://github.com/owid/owid-grapher/assets/11844404/e77ec071-5a8f-4a4a-aa88-e698a8a5db2f">

This calculation isn't working correctly for Windows browsers for some reason, which is causing the Research & Writing block article rows to exceed the bounds of the centred column.

In this [Browserstack test](https://www.browserstack.com/screenshots/b06da191ac0070822b7e1c231c247cf890c93892) you can scroll down to the Research & Writing section on each page and see a printout of the column width.

Either via a VM or Windows machine, we'll need to investigate why this calculation is off and how it can be fixed.
