### ISSUE TITLE
Multi-dim dropdown with only one option shouldn't be changeable

### ISSUE THREAD

**Issue by rakyi** [owid/owid-grapher#4882]
## Description

It's confusing when there is only one option available in an mdim dropdown. This can happen when there are more options available in other views, otherwise we shouldn't have a dropdown for that dimension at all.

## Expected behaviour

When there is only one option available in an mdim dropdown, the dropdown should be disabled.

**Comment by pabloarosado** [comment]
Thanks Martin! I think fixing this soon would be helpful to be able to publish the first poverty mdims.

**Comment by lucasrodes** [comment]
Nice that we are looking at this! I've been thinking of this in the context of a dimension "not really applying" to a view, which I think is a bit related. Let me elaborate below, but also happy to chat about it any time.

At the moment, we can have a single choice in a dimension dropdown for two reasons:

**1) There is actually only one choice. [Example](https://admin.owid.io/admin/grapher/energy%2Flatest%2Fenergy_prices%23energy_prices?source=electricity&frequency=monthly&price_component=wholesale&consumer=all&unit=euro)**
<img width="1018" alt="Image" src="https://github.com/user-attachments/assets/bc0430e4-5e71-4e7c-b84a-2c3261dbee22" />


**2) There are no choices; we fill the dropdown with something like `Not applicable`. [Example](https://admin.owid.io/admin/grapher/war%2Flatest%2Fmars%23mars?indicator=wars_ongoing&estimate=na)**

<img width="823" alt="Image" src="https://github.com/user-attachments/assets/d08ae059-879b-4675-a296-dcd77d74a117" />


I think that Grapher should treat these two cases differently.

For 1, I think that simply graying out or disabling the dropdown when it detects a single choice should suffice. This is similar to what we have for Explorers.

For 2, I've been wondering what the best strategy is. At the moment, each view in an MDIM needs to have all its dimensions specified; otherwise, it is not clear which dimension choice selection it should be shown for. Taking the example above from 2, this is how the `view` is defined:

```yaml
dimensions:
  indicator: wars_ongoing
  estimate: na
indicators:
  y:
    - catalogPath: grapher/war/2023-09-21/mars/mars#number_ongoing_conflicts__conflict_type_civil_war
       display:
         name: Civil wars
    - catalogPath: grapher/war/2023-09-21/mars/mars#number_ongoing_conflicts__conflict_type_others__non_civil
       display:
         name: Interstate wars
```

How the dropdowns are displayed is specified by the corresponding `dimension` field, where a name, description and group can be specified: 

```yaml
- slug: estimate
   name: "Estimate"
   choices:
      - slug: low
        name: Low estimate
      - slug: high
        name: High estimate
      - slug: na
        name: "Not applicable"
        # description: "Not applicable"
      - slug: low_high
        name: "Low and high estimates"
```

I wondered if we could add a new property of `dimension`, which tells what choice (if any) should be considered as "NA". So, re-writing the above code:


```yaml
- slug: estimate
   name: "Estimate"
   presentation:
     slug_choice_na: na
   choices: ...
```

Note: I added property `slug_choice_na` under `presentation` because I think that we may want to add more display settings in the future. E.g. widget type (dropdown, checkbox, etc.), and maybe we want to have them under the same group, but unsure.


**Final notes:** I think that a strategy like this wouldn't break anything. I am just cautious of breaking the fundamental assumption of all views in an MDIM, requiring all dimensions to be specified.
