### ISSUE TITLE
MDIMs: View metadata for `description_key` is wrongly set

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#5007]
_[Slack discussion](https://owid.slack.com/archives/C071F90MD0X/p1750333680981919)_
## Description
In ETL, we should be able to customize the metadata of each view. However, `description_key` doesn't work as one would expect. Instead, it looks as if it combined the manual edits with the indicator's original key points.

## Expected behaviour
Given a view, whatever value I set to `description_key` should be the one shown in the UI.

## Steps to reproduce

1. Go to this [demo](http://staging-site-bug-demo-metadata/admin/grapher/dummy%2Flatest%2Fdemo%23demo?view=view_1) (corresponds to[ this PR](https://github.com/owid/etl/pull/4597))
2. Just look at the bullet points for the view `View="With edits"` and you will see that there is not just one key point but more.

### MDIM configuration
```yaml
title:
  title: Demo for raising issues with MDIMs
  title_variant: ""
default_selection:
  - World

dimensions:
  - slug: view
    name: View
    choices:
      - slug: view_1
        name: With edits
        description: View with custom edits done for the MDIM. This shows the bug.
      - slug: view_2
        name: No edits
        description: No edits done to the metadata/config.

views:
  - dimensions:
      view: view_1
    indicators:
      y:
        - catalogPath: grapher/covid/latest/cases_deaths/cases_deaths#weekly_cases
    metadata:
      description_key:
        - I've manually set just one description key for this view. However, some of the original indicator's description keys are still visible! Namely all but the first one (which has been replaced)

  - dimensions:
      view: view_2
    indicators:
      y:
        - catalogPath: grapher/covid/latest/cases_deaths/cases_deaths#weekly_cases
```

### Description key of the first view
Although I've customized it and set just one description key, it continues to show some of the original indicator's bullet points. 

There were originally 4 key points, and I've set one. Mine is shown first, and then the 2nd, 3rd, and 4th from the original list are shown. It looks like: if there were `N` key points and I've manually set `M` it acts as:

- If `N` > `M`: First my `M` points are shown, then the remaining from `N` starting at the `Mth` position
- if `N` <= `M`: Just my `M` points are shown 

<img width="892" alt="Image" src="https://github.com/user-attachments/assets/0add35d5-840c-4648-8260-7a6e28623689" />

## Additional issue
I am observing that the view with `View="No edits"` also shows the manually added description key bullet point. Both views use the same indicator, so maybe there is something going wrong in the baking because of that?
