### ISSUE TITLE
MDIMs: spacing in group labels feels out of place sometimes

### ISSUE THREAD

**Issue by lucasrodes** [owid/owid-grapher#5017]
## Description
The spacing in group labels feels out of place when not all choices have a group assigned.

## More context
I've drafted [this MDIM](http://staging-site-bug-titlepublic-mdims-issue/admin/grapher/dummy%2Flatest%2Fissue_reporting%23issue_reporting), which uses `group` for the last view (see config below).

```yaml
dimensions:
  - slug: view
    name: View
    choices:
      - slug: view_1
        name: With edits
        description: View with custom edits done for the MDIM. This shows the bug.
      - slug: view_2
        name: No edits
        description: No edits done to the metadata/config.
      - slug: view_combined
        name: Combined view
        description: This view combines the two above views, and should show the edits from view_1.
        group: Grouped views
```

The group label seems to be out of place, too close to the previous choice.

## Screenshots
See the label "Grouped views", which looks too close to the horizontal separator line.

![Image](https://github.com/user-attachments/assets/e2268da6-ae64-48e4-ae91-40ef2d87792e)
